### ISSUE TITLE
Incorrect indentation for hash as a function parameter

### ISSUE THREAD

**Issue by joshuaspence** [relud/puppet-lint-strict_indent-check#11]
This rule seems to work as expected for the following code snippet:

```puppet
class { 'foo':
  param => {
    foo => 'bar',
    bar => 'baz',
  },
}
```

However, it doesn't work as I would have expected for this (similar) snippet:

```puppet
class { 'bar':
  param => epp('template.epp', {
    foo => 'bar',
    bar => 'baz',
  }),
}
```

```
WARNING: indent should be 6 chars and is 4 on line 3
WARNING: indent should be 6 chars and is 4 on line 4
```

**Comment by relud** [comment]
this behavior is intended, so that there is a clear solution to this block:

<pre>
class { 'bar':
  param => epp('template.epp', {
      foo => 'bar',
      bar => 'baz',
    }
  ),
}
</pre>
