### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by alexjfisher** [relud/puppet-lint-strict_indent-check#3]
Due to https://github.com/relud/puppet-lint-strict_indent-check/pull/2 would it be possible to have a new release published to rubygems?

Many thanks.

**Comment by relud** [comment]
Yeah, i'll try to publish something later today or early next week

**Comment by alexjfisher** [comment]
Thanks.  Apologies for repeating myself BTW. https://github.com/relud/puppet-lint-strict_indent-check/pull/2#issuecomment-228000345

I know how easy it is to miss github notifications though (I get hundreds), so I hope you didn't mind.

**Comment by relud** [comment]
not a problem at all :)

**Comment by relud** [comment]
fixed in 2.0.2
