### ISSUE TITLE
puppet-lint >=2.0

### ISSUE THREAD

**Issue by wybczu** [relud/puppet-lint-strict_indent-check#7]
Right know puppet-lint-strict_indent-check requires puppet-lint > 1.0. Are there any plans for releasing new version with support for puppet-lint >= 2.0?

**Comment by relud** [comment]
It does support >= 2.0, it just also supports 1.x.

**Comment by wybczu** [comment]
Oh, I'm sorry, that's correct - I had pinned 2.0.1 version of puppet-lint-strict_indent-check :(
